# Generated by Django 2.0.4 on 2018-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('group_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('welcome_msg', models.TextField(default='{}')),
            ],
        ),
    ]
