version: '3'
services:
  db:
    image: mysql:5.6
    container_name : otterbot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FFXIV_DEV
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    networks:
      - otterbot_network
  web:
    container_name : otterbot-web
    image: 'bluefissure/otterbot:latest'
    build: .
    depends_on:
      - db
      - redis
      - rabbit
    environment:
      FFXIVBOT_ROOT: /FFXIVBOT/
      TULING_API_KEY: 123
      BOT_FATHER: 爸爸
      BOT_MOTHER: 妈妈
      USER_NICKNAME: 光呆呆
    networks:
      - otterbot_network
    ports:
      - 8000:8002
    restart: always
    command: bash docker-entrypoint.sh
    links:
      - db
      - redis
      - rabbit
  redis:
    container_name : otterbot-redis
    image: "redis:alpine"
    networks:
      - otterbot_network
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    container_name : otterbot-rbq
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    networks:
      - otterbot_network
networks:
  otterbot_network:
volumes:
  mysql-data:
